---
- name: Install TFTP
  ansible.builtin.package:
    state: present
    name: tftp-server

- name: Allow TFTP traffic in firewalld on port
  ansible.posix.firewalld:
    service: tftp
    permanent: true
    state: enabled
    immediate: true

- name: Copy tftp systemd file
  ansible.builtin.template:
    src: tftp.service.j2
    dest: /etc/systemd/system/tftp.service
    owner: root
    group: root
    mode: '0644'
  notify: TFTP service restart

- name: Start and enable tftp service
  ansible.builtin.service:
    name: tftp
    state: started
    enabled: true
    daemon_reload: true
